doctrine:
    dbParams:
        driver:   pdo_mysql
        host:     localhost
        charset:  utf8
        user:     root
        password: ''
        dbname:   blog

    ormConfig:
        entitiesPath:
            path: 'src/JHD/Entity'
        isDevMode: true
        proxyDir: null
        cache: null
        useSimpleAnnotationReader: false

twig:
    templatePath: 'src/JHD/Views'
    defaultFormThemePath: 'bootstrap_3_layout.html.twig'
    bridgePath: 'vendor/symfony/twig-bridge/Resources/views/Form'
    options:
        cache: cache
        debug: true

symfony:
    formTranslationPath: 'vendor/symfony/form/Resources/translations/validators.fr.xlf'
    validatorTranslationPath: 'vendor/symfony/validator/Resources/translations/validators.fr.xlf'

swift_mailer:
    smtpHost: 'smtp.gmail.com'
    port: 465
    userName: 'xtrazyx@gmail.com'
    password: 'xanaxaego666'
    encryption: 'ssl'
    setFrom: 'xtrazyx@gmail.com'
    name: 'Julien Habert'