index:
    url:        /
    controller: Index
    bundle: JHD\Blog

post_list:
    url:        /posts
    controller: PostList
    bundle: JHD\Blog

post:
    url:        /post-([0-9]+)-(.*)
    controller: Post
    bundle: JHD\Blog
    vars:
        id: 1
        title: ''

add_post:
    url:        /add_post
    controller: AddPost
    bundle: JHD\Blog

edit_post:
    url:        /edit_post-([0-9]+)-(.*)
    controller: EditPost
    bundle: JHD\Blog
    vars:
        id: 1
        title: ''

add_comment:
    url:        /add_comment-([0-9]+)
    controller: AddComment
    bundle: JHD\Blog
    vars:
        post_id: 1